### ISSUE TITLE
En mode Dome, si ControlGris envoie de l'OSC et qu'on ferme la fenêtre de Speaker Setup Edition après avoir fait des modifications du setup, SpatGRIS gèle.

### ISSUE THREAD

**Issue by DavidPiazza** [GRIS-UdeM/SpatGRIS#367]
Version 3.1.14
macOS 12.5.1 Monterey
Intel Core i5

Au chargement d'un speaker setup existant sur le disque dur, SpatGris plante si une instance de ControlGris est en train d'envoyer des données de spatialisation automatisées.

Le problème ne survient pas si on charge un speaker setup template.

Étapes à suivre pour reproduire le problème : 

1. Créer une ligne d'automatisation modifiant l'emplacement d'une source et démarrer le transport;
2. Ouvrir SpatGris;
3. Charger un speaker setup existant (qu'il ait été créé avec la version courante de SpatGris n'a pas d'importance).

Si on modifie le speaker setup courant (par exemple, en modifiant le potentiomètre Global Sound Diffusion) SpatGris nous propose de sauvegarder le speaker setup puisqu'il a été modifié. Une réponse affirmative cause un crash si des données de spatialisation sont envoyées par ControlGris.

Solution : Arrêter la lecture de l'automatisation dans la station de travail avant d'apporter des modifications au Speaker Setup actif.

**Comment by DavidPiazza** [comment]
Si on modifie le speaker setup courant (par exemple, en modifiant le potentiomètre Global Sound Diffusion) SpatGris nous propose de sauvegarder le speaker setup puisqu'il a été modifié. Une réponse affirmative cause un crash si des données de spatialisation sont envoyées par ControlGris.

**Comment by DavidPiazza** [comment]
Solution : Arrêter la lecture de l'automatisation dans la station de travail avant d'apporter des modifications au Speaker Setup actif.

**Comment by Normandeau** [comment]
Merci pour ces tests. On pourra ajouter ces informations dans le manuel. Cependant je ne crois pas que cela affecte l'usage courant de nos outils.

**Comment by DavidPiazza** [comment]
Je propose qu'on réouvre cette issue, dans la mesure où le nouveau paramètre Global Sound Diffusion suppose qu'on l'ajuste dans la fenêtre _Speaker Setup Edition_ alors qu'on écoute la spatialisation de la pièce. 

Suggestion de solution : Empêcher la sauvegarde d'un speaker setup si SpatGRIS détecte la réception de messages OSC à son port d'entrée, tout en avisant l'utilisateur.trice d'arrêter la lecture de son projet avant de procéder à l'enregistrement du setup pour éviter un crash.

**Comment by Normandeau** [comment]
V320
Je n'arrive pas à reproduire ce bogue. J'ai suivi exactement la procédure décrite par David. J'ai tout changé dans la fenêtre Speaker Edition pendant que SpatGRIS reçoit de l'OSC. Je sauve le résultat et tout continue à rouler normalement. 
Est-ce que parce que la versison 320 a corrigé le problème déjà?
David, peux-tu confirmer?

**Comment by NicolaGiannini** [comment]
V320
Moi non plus j'arrive à reproduire ce bogue. 
J'ai essayé de :

- Changer de Speaker Setup (à partir des templates et aussi des fichiers créés par moi sur mon ordi)
- Sauvegarder des modifications au Speaker Setup

Tout cela pendant que ControlGRIS envoie des données OSC.

Pas de plantage de mon côté non plus.

**Comment by DavidPiazza** [comment]
https://user-images.githubusercontent.com/50223477/196547273-93e80fb7-ae02-4a48-aef9-9af25169ee68.mov

https://user-images.githubusercontent.com/50223477/196547471-d1bb1f32-c6bd-4a40-8a8f-b4722e3accbf.mov

Et bien, je vous envie! C'est probablement un problème du côté de ma machine alors. J'essaierai de faire des tests sur mon iMac également. Ci-haut, deux exemples où je modifie un template en dôme alors que SpatGris reçoit des données OSC. Que j'appuie sur oui ou non, un crash survient. À noter que la « balloune de plage » de macOS n'apparaît pas dans les captures d'écran.

En mode cube toutefois, je n'ai plus de crash quand je modifie le Global Sound Diffusion, SpatGris me permet de sauvegarder le setup. Je suppose que le problème est donc réglé, puisque c'est le seul paramètre qui suppose qu'on le modifie alors qu'on écoute la pièce.

https://user-images.githubusercontent.com/50223477/196548406-045a3704-ed6d-4f11-9dd5-785fc4909998.mov

**Comment by Normandeau** [comment]
Je remarque que la description du crash que tu fais change d'une fois à l'autre.
1-Voici ce que tu dis en premier, qui est le titre de cette issue:
«Au chargement d'un speaker setup existant sur le disque dur, SpatGris plante si une instance de ControlGris est en train d'envoyer des données de spatialisation automatisées.»
Bon je ne pense que ça soit une bonne idée de changer le Speaker Setup «pendant» qu'on envoie de l'OSC! Qui a besoin de cela?
2-Ensuite tu parles Global Sound Diffusion, ce qui implique le mode Cube. Situation qu'on n'a pas été en mesure de reproduire et qui semble réglée.
3- Finalement du parles du mode Dome. Voyons voir ce qui en est. En effet, SpatGRIS gèle (il ne crashe pas), lorsqu'après avoir effectué une modification dans le speaker setup, on ferme la fenêtre. Mais si on utilise Save, ou Save As ça fonctionne.
Donc la question demeure: à qui cela est-il utile d'envoyer de l'OSC en modifiant le Speaker Setup?
4-Testé en modifiant le Gain et le HighPass. Pendant une calibration en salle, on peut avoir besoin de faire tourner le son, et ajuster le gain ou le Highpass des hp. Même résultat: le Save et le Save As fonctionnent, mais si on ferme la fenêtre avant de le faire, SpatGRIS gèle. Il faut alors le forcer à quitter. Très bizarrement, ce comportement n'existe pas en mode Cube.
Voilà, c'est plus précis.

**Comment by DavidPiazza** [comment]
> 2-Ensuite tu parles Global Sound Diffusion, ce qui implique le mode Cube. Situation qu'on n'a pas été en mesure de reproduire et qui semble réglée.

Ça semble en effet réglé, comme je l'ai mentionné en conclusion de mon dernier commentaire. Pas de crash quand je modifie le Global Sound Diffusion.

**Comment by Normandeau** [comment]
David,

Oui ce que je voulais dire c'est que lorsqu'on rapporte un bogue, il fait le décrire le plus précisément possible.
Et je dirais: le plus simplement possible.
Et en utilisant les bons mots aussi.
Crache et gèle ne décrivent pas la même situation par exemple.
Du point de vue du programmeur, cela donne des indices différents.
Un gel peut donner un indice d'un calcul interminable alors qu'un crache indique plutôt un conflit.
Les solutions ne sont pas du même ordre.

Les trois situations que tu décris dans ton message initial sont toutes intriquées les unes dans les autres.
Il se peut qu'elles soient reliées, mais aussi qu'elles ne le soient pas.
Comme cela semble bien être le cas ici par exemple.

En les décrivant séparément, on aide le programmeur à mettre le doigt dessus plus rapidement et à trouver une ou des solutions reliées à chaque cas.
Cela nous oblige aussi à tester systématiquement un problème afin d'en bien cerner les contours.
Plutôt que juste dire: ça crache.

Comme je te le disais, c'est le métier qui entre!
Merci pour toutes tes contributions.

Le 18 oct. 2022 à 18:52, David Piazza ***@***.******@***.***>> a écrit :



2-Ensuite tu parles Global Sound Diffusion, ce qui implique le mode Cube. Situation qu'on n'a pas été en mesure de reproduire et qui semble réglée.

Ça semble en effet réglé, comme je l'ai mentionné en conclusion de mon dernier commentaire. Pas de crash quand je modifie le Global Sound Diffusion.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGRIS-UdeM%2FSpatGRIS%2Fissues%2F367%23issuecomment-1283100776&data=05%7C01%7Crobert.normandeau%40umontreal.ca%7C829a11162f094e56f46e08dab15b634c%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638017303304272048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HIJlSnHivgBmj3o41NzChW6set7IDESKWx%2FwVDLRPPY%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACELOI6NQO2WE4VL4KKFQADWD4SZRANCNFSM6AAAAAAQRRHMQM&data=05%7C01%7Crobert.normandeau%40umontreal.ca%7C829a11162f094e56f46e08dab15b634c%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638017303304272048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YfBVezwWYV9RynK%2BJJ3qDJh%2Fqr5ZoBkjQR4bIEw4heU%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Cordialement,

•••••••••••••••••
Robert Normandeau
Professeur titulaire de composition électroacoustique
Directeur du GRIS
Faculté de musique

T 514-343-6111 poste 3486

Faculté de musique
200, ave. Vincent d'Indy
Bureau  A-879, Montréal, H2V 2T2

[cid:FA2B6DA7-5371-4FCD-B945-B8CC52684843]

**Comment by DavidPiazza** [comment]
Je comprends! Merci pour vos commentaires et conseils. À l'avenir, j'utiliserai les termes précis, et décrirai les situations de manière plus succincte.

**Comment by Normandeau** [comment]
V321
Cela semble réglé, autant mode Dome qu'en mode Cube. À confirmer svp.

**Comment by NicolaGiannini** [comment]
V321
Cela semble réglé, en mode Dome, Cube et Hybrid.
