### ISSUE TITLE
Sound source not moving between speakers

### ISSUE THREAD

**Issue by mkschulze** [GRIS-UdeM/SpatGRIS#387]
Hello,

I have the following setup:

macOS Ventura 13.1
iMac with 32GB RAM, i7 Comet Lake
Bitwig 4.4.6
SpatGRIS 3.2.1

I recorded this video to illustrate my issue: https://www.dropbox.com/s/dk218pth5vd9eak/2023-01-03%2016-49-27.mkv?dl=0

Explanation:

I setup Blackholw 128 as output device in Bitwig and as an input device in SpatGRIS.
Then I created a track and inserted ControlGRIS on it, set source to 2 and sending out the signal on channel 3/4. This arrives then in SpatGRIS on track 3/4. So the routing is working.

I chose the Cube 4 speaker setting.

However, I cannot make the sound source move in between all available speakers, I'd think, that when I move the sound source on ControlGRIS closer to speaker 1/2, then the signal would be distributed on channel 1/2 instead of 3/4, right?

How can this be achieved, and do I really have to setup the hard channel routing from the input channels to the outputs like here?
![Screenshot 2023-01-03 at 17 01 01](https://user-images.githubusercontent.com/3390820/210394338-a68285ba-23d0-46da-9c89-4b051dee3996.png)

I don't really understand how this can be achieved, if I do not set anything here, then there is no sound arriving on the outputs, but in your video explanation on the homepage, you do not set these outputs.

![Screenshot 2023-01-03 at 17 02 39](https://user-images.githubusercontent.com/3390820/210394705-d244fddf-89bf-4429-8ef1-3b49e3909297.png)

The signal always is distributed through channel 3/4 currently, so I cannot make any use of spatialisation or 3D movements.

Thanks for your help!
Mark

**Comment by Normandeau** [comment]
Mark,

Happy new year at first.

Reading the manual would certainly help you.
Your problem is the most basic one in the communication between ControlGRIS and SpatGRIS.


Please refer to the manual page 16:

*****
First Source ID <>
This number should be unique and different for each audio channel. You must set the same numbers for audio and for OSC.

If you have only mono tracks, the numbers are successive. If you have stereo tracks, you'll have only odd numbers to put here: 1, 3, 5, etc. because the even numbers are set automatically to the right channel of each stereo track. And if you work with octophonic sound files, the first source ID will be 1, the second octophonic track will start at 9, etc.

*****

So in your example, you send the audio on outputs 3-4 and OSC to channel 1-2...

Have fun.

**Comment by mkschulze** [comment]
Oh, thanks! I read that part a few times, but still missed it somehow.
